sudo: required
dist: bionic

language: bash

install:
  - echo "verbose = off" >> ~/.wgetrc
  - sed -i 's/install-boost/install-boost > boostlog.log/' ARM-RStudio.sh
  - sed -i 's/apt-get install/apt-get -qq install/' ARM-RStudio.sh
  - echo 'Beginning install'
script:
  - # travis disabled VM and containers with sudo, so this script can't run now
  - #sudo travis wait 30 ./ARM-RStudio.sh
